apiVersion: apps/v1
kind: Deployment
metadata:
  name: maduvan-bank-gke-frontend-deployment
spec:
  selector:
    matchLabels:
      app: bank-gke-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: bank-gke-frontend
    spec:
      containers:
      - name: bank-gke-frontend
        image: us-east1-docker.pkg.dev/gcp-class-17/maduvan-gke-repo/bank-gke-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: maduvan-bank-gke-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: bank-gke-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
